services:
  - type: web
    name: teams-voice-extension
    runtime: node
    plan: starter  # Free tier
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      # Azure OpenAI environment variables (you'll need to add these in Render dashboard)
      - key: AZURE_OPENAI_ENDPOINT
        sync: false
      - key: AZURE_OPENAI_API_KEY
        sync: false
      - key: AZURE_OPENAI_DEPLOYMENT_NAME
        sync: false
      - key: AZURE_OPENAI_WHISPER_DEPLOYMENT
        sync: false
      - key: AZURE_OPENAI_API_VERSION
        sync: false